#!/usr/bin/python

# Copyright (C) 2010,2011 Javier Palacios
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License Version 2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.


__version__ = "1.0"

__usage__ = """Usage : %s repo_name subrepo"""


import repolib
import os , sys


if sys.argv[1:] :
    if len(sys.argv) != 3 :
        print __usage__
        sys.exit(-1)
    repo_name , subrepo = sys.argv[1:3]
else :
    print __usage__
    sys.exit(-1)

repolib.logger.setLevel( repolib.logging.CRITICAL )


try :
    repo = repolib.MirrorRepository.new( repo_name )
    repo.select_component( subrepo )
    repo.set_mode( "keep" )
except Exception , ex :
    print "UNKNOWN - Cannot process %s %s : %s" % ( repo , subrepo , ex )
    sys.exit(3)


meta_files = repo.get_metafile()
local_repodata = repo.write_master_file( meta_files )
packages = repo.subrepos[subrepo].get_metafile( local_repodata )

for file in meta_files.values() :
    if not isinstance(file,bool) :
        os.unlink( file )

msg = "OUTDATED - %s %s" % ( repo , subrepo )
retcode = 2

if packages is True :
    msg = "OK - %s %s is up to date" % ( repo , subrepo )
    retcode = 0
elif packages :
    os.unlink( packages )

print msg
sys.exit(retcode)

