
DONE = False

APLOG_CRITICAL = "CRITICAL"
APLOG_ERROR    = "ERROR"
APLOG_INFO     = "INFO"
APLOG_DEBUG    = "DEBUG"

# BaseHTTPServer.BaseHTTPRequestHandler.responses
OK = 200
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_NOT_FOUND = 404

